syncSource:
  replicaSet:
    hostAndPort: "mongodb:27017"
    scramAuth:
      username: "mongotUser"
      passwordFile: "/secrets/passwordFile"
      authSource: "admin"
      tls:
        enabled: false
  replicationReader:
    readPreference: "secondaryPreferred"

storage:
  dataPath: "/data/mongot"

server:
  name: careercoach-mongot
  grpc:
    address: "mongot:27028"
    tls:
      mode: "disabled"

metrics:
  enabled: true
  address: "mongot:9946"

healthCheck:
  address: "mongot:8080"

logging:
  verbosity: INFO
