import type { CatalogAction, CatalogResource, StageTemplate } from "./catalog.types";

/**
 * Ordered experience arc. Each stage index maps to at most one template so titles stay unique.
 * Overflow stages get numbered experience labels instead of repeating "Prepare for…".
 */
export const STAGE_TEMPLATES: readonly StageTemplate[] = [
    {
        id: "tpl.foundations",
        labelPattern: "Build {focus} foundations",
        descriptionPattern:
            "Build foundational knowledge in {focus}. Use projects and deliberate practice so later roles have something real to stand on toward {dreamJob}.",
        whyItMattersPattern: "Without this foundation, later experience stages for {dreamJob} will stall.",
        progressionType: "learning",
        categories: ["technical", "domain", "credential"],
        maxGaps: 3,
    },
    {
        id: "tpl.domain.experience",
        labelPattern: "Gain hands-on {focus} experience",
        descriptionPattern:
            "Move from study into real work: roles, projects, or scoped assignments that create proof of {focus} capability on the path to {dreamJob}.",
        whyItMattersPattern: "Experience compounds; this stage creates evidence employers and future teams can trust.",
        progressionType: "experience",
        categories: ["experience", "technical", "domain"],
        maxGaps: 3,
    },
    {
        id: "tpl.specialize",
        labelPattern: "Deepen {focus} judgment",
        descriptionPattern:
            "Specialize in {focus} through harder problems, reviews, and ownership so your knowledge becomes usable under pressure toward {dreamJob}.",
        whyItMattersPattern: "Depth separates operators from leaders in the {dreamJob} journey.",
        progressionType: "hybrid",
        categories: ["architecture", "technical", "domain"],
        maxGaps: 3,
    },
    {
        id: "tpl.apply",
        labelPattern: "Own outcomes with {focus}",
        descriptionPattern:
            "Take end-to-end responsibility where {focus} is the lever. Ship outcomes, write retros, and collect measurable results.",
        whyItMattersPattern: "Ownership evidence is required before senior and executive scope for {dreamJob}.",
        progressionType: "experience",
        categories: ["responsibility", "experience", "soft"],
        maxGaps: 3,
    },
    {
        id: "tpl.lead",
        labelPattern: "Lead people and programs in {focus}",
        descriptionPattern:
            "Grow leadership impact around {focus}: mentor others, run programs, and make tradeoffs that affect a team—not only your own tickets.",
        whyItMattersPattern: "CEO-track roles require people and program leadership, not only individual skill.",
        progressionType: "experience",
        categories: ["leadership", "responsibility"],
        maxGaps: 3,
    },
    {
        id: "tpl.business",
        labelPattern: "Build business fluency around {focus}",
        descriptionPattern:
            "Learn how {focus} connects to customers, revenue, risk, and P&L so technical strength becomes company-level decision making for {dreamJob}.",
        whyItMattersPattern: "Executive roles fail when domain experts cannot translate work into business outcomes.",
        progressionType: "hybrid",
        categories: ["domain", "leadership", "responsibility"],
        maxGaps: 3,
    },
    {
        id: "tpl.target",
        labelPattern: "Package evidence for {dreamJob}",
        descriptionPattern:
            "Consolidate experience, narrative, and network so you can pursue {dreamJob} opportunities with credible proof—not just intent.",
        whyItMattersPattern: "The final stage converts accumulated experience into a hireable executive story.",
        progressionType: "hybrid",
        categories: ["soft", "experience", "leadership"],
        maxGaps: 3,
    },
] as const;

export const ACTIONS_CATALOG: readonly CatalogAction[] = [
    {
        id: "act.study.fundamentals",
        title: "Complete a structured fundamentals learning plan with weekly projects",
        capabilityIds: ["cap.programming.fundamentals"],
        effortHours: 120,
        minCalendarWeeks: 12,
        progressionType: "learning",
    },
    {
        id: "act.credential.degree",
        title: "Complete a CS bachelor's (or equivalent experience portfolio spanning multi-year depth)",
        capabilityIds: ["cap.credential.cs.degree"],
        effortHours: 3600,
        minCalendarWeeks: 156,
        progressionType: "learning",
    },
    {
        id: "act.practice.javascript",
        title: "Build small JavaScript projects with tests",
        capabilityIds: ["cap.javascript"],
        effortHours: 80,
        minCalendarWeeks: 8,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.typescript",
        title: "Migrate a project to TypeScript with strict settings",
        capabilityIds: ["cap.typescript"],
        effortHours: 60,
        minCalendarWeeks: 6,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.react",
        title: "Ship a React UI with accessible components",
        capabilityIds: ["cap.react"],
        effortHours: 80,
        minCalendarWeeks: 8,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.python",
        title: "Complete Python exercises and a data script",
        capabilityIds: ["cap.python"],
        effortHours: 80,
        minCalendarWeeks: 8,
        progressionType: "learning",
    },
    {
        id: "act.practice.sql",
        title: "Write SQL queries against a sample dataset",
        capabilityIds: ["cap.sql"],
        effortHours: 40,
        minCalendarWeeks: 4,
        progressionType: "learning",
    },
    {
        id: "act.study.cyber",
        title: "Complete a cybersecurity fundamentals path (networks, threats, controls) with labs",
        capabilityIds: ["cap.cybersecurity"],
        effortHours: 200,
        minCalendarWeeks: 26,
        progressionType: "learning",
    },
    {
        id: "act.experience.secops",
        title: "Accumulate SOC / incident-response experience via job, internship, or volunteer blue-team work",
        capabilityIds: ["cap.security.operations"],
        effortHours: 800,
        minCalendarWeeks: 52,
        progressionType: "experience",
    },
    {
        id: "act.study.sec.architecture",
        title: "Design and review security architectures for real systems; document tradeoffs",
        capabilityIds: ["cap.security.architecture"],
        effortHours: 300,
        minCalendarWeeks: 39,
        progressionType: "hybrid",
    },
    {
        id: "act.study.system.design",
        title: "Document a system design for a familiar product",
        capabilityIds: ["cap.system.design"],
        effortHours: 100,
        minCalendarWeeks: 12,
        progressionType: "learning",
    },
    {
        id: "act.practice.cloud",
        title: "Deploy and harden a sample service in a cloud provider",
        capabilityIds: ["cap.cloud.basics"],
        effortHours: 80,
        minCalendarWeeks: 8,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.devops",
        title: "Add CI pipeline and containerized local run",
        capabilityIds: ["cap.devops.basics"],
        effortHours: 80,
        minCalendarWeeks: 10,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.data",
        title: "Analyze a dataset and summarize insights",
        capabilityIds: ["cap.data.analysis"],
        effortHours: 60,
        minCalendarWeeks: 6,
        progressionType: "learning",
    },
    {
        id: "act.practice.ml",
        title: "Train and evaluate a baseline ML model",
        capabilityIds: ["cap.machine.learning"],
        effortHours: 120,
        minCalendarWeeks: 16,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.product",
        title: "Write a product brief with success metrics for a security or platform problem",
        capabilityIds: ["cap.product.sense"],
        effortHours: 40,
        minCalendarWeeks: 8,
        progressionType: "learning",
    },
    {
        id: "act.practice.business",
        title: "Build a simple P&L / unit-economics model for a security product or services line",
        capabilityIds: ["cap.business.finance"],
        effortHours: 160,
        minCalendarWeeks: 26,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.communication",
        title: "Prepare and deliver a stakeholder update with decisions and risks",
        capabilityIds: ["cap.communication"],
        effortHours: 40,
        minCalendarWeeks: 4,
        progressionType: "experience",
    },
    {
        id: "act.practice.collaboration",
        title: "Lead a cross-functional task with written handoff",
        capabilityIds: ["cap.collaboration"],
        effortHours: 60,
        minCalendarWeeks: 8,
        progressionType: "experience",
    },
    {
        id: "act.practice.leadership",
        title: "Lead a team or program for a sustained period; capture mentorship and delivery outcomes",
        capabilityIds: ["cap.leadership"],
        effortHours: 600,
        minCalendarWeeks: 52,
        progressionType: "experience",
    },
    {
        id: "act.practice.executive",
        title: "Run executive-level work: strategy memos, board-style updates, and multi-team prioritization",
        capabilityIds: ["cap.executive.leadership"],
        effortHours: 800,
        minCalendarWeeks: 78,
        progressionType: "experience",
    },
    {
        id: "act.practice.ownership",
        title: "Own a business-critical deliverable end-to-end with a retrospective",
        capabilityIds: ["cap.project.ownership"],
        effortHours: 160,
        minCalendarWeeks: 16,
        progressionType: "experience",
    },
    {
        id: "act.practice.domain",
        title: "Research domain workflows and map key stakeholders and failure modes",
        capabilityIds: ["cap.domain.business"],
        effortHours: 80,
        minCalendarWeeks: 12,
        progressionType: "learning",
    },
    {
        id: "act.practice.interview",
        title: "Complete timed mock interviews with self-review",
        capabilityIds: ["cap.interview.ready"],
        effortHours: 40,
        minCalendarWeeks: 4,
        progressionType: "hybrid",
    },
    {
        id: "act.practice.portfolio",
        title: "Publish portfolio case studies that show security impact and business outcomes",
        capabilityIds: ["cap.portfolio"],
        effortHours: 80,
        minCalendarWeeks: 8,
        progressionType: "experience",
    },
    {
        id: "act.practice.experience",
        title: "Hold cybersecurity roles (intern → IC → senior) long enough to build credible tenure",
        capabilityIds: ["cap.professional.experience"],
        effortHours: 1000,
        minCalendarWeeks: 52,
        progressionType: "experience",
    },
    {
        id: "act.experience.generic",
        title: "Build deliberate practice and workplace evidence for this capability over months",
        capabilityIds: [],
        effortHours: 120,
        minCalendarWeeks: 12,
        progressionType: "experience",
    },
] as const;

export const RESOURCES_CATALOG: readonly CatalogResource[] = [
    {
        id: "res.mdn.javascript",
        title: "MDN JavaScript Guide",
        platform: "MDN",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
        type: "docs",
        capabilityIds: ["cap.javascript"],
        effortHours: 8,
    },
    {
        id: "res.typescript.handbook",
        title: "TypeScript Handbook",
        platform: "TypeScript",
        url: "https://www.typescriptlang.org/docs/handbook/intro.html",
        type: "docs",
        capabilityIds: ["cap.typescript"],
        effortHours: 8,
    },
    {
        id: "res.react.docs",
        title: "React Official Docs",
        platform: "React",
        url: "https://react.dev/learn",
        type: "docs",
        capabilityIds: ["cap.react"],
        effortHours: 10,
    },
    {
        id: "res.python.tutorial",
        title: "Python Official Tutorial",
        platform: "Python",
        url: "https://docs.python.org/3/tutorial/",
        type: "docs",
        capabilityIds: ["cap.python"],
        effortHours: 8,
    },
    {
        id: "res.sql.bolt",
        title: "SQLBolt Interactive Lessons",
        platform: "SQLBolt",
        url: "https://sqlbolt.com/",
        type: "practice",
        capabilityIds: ["cap.sql"],
        effortHours: 6,
    },
    {
        id: "res.nist.cyber",
        title: "NIST Cybersecurity Framework",
        platform: "NIST",
        url: "https://www.nist.gov/cyberframework",
        type: "docs",
        capabilityIds: ["cap.cybersecurity", "cap.security.architecture"],
        effortHours: 12,
    },
    {
        id: "res.owasp.top10",
        title: "OWASP Top 10",
        platform: "OWASP",
        url: "https://owasp.org/www-project-top-ten/",
        type: "docs",
        capabilityIds: ["cap.cybersecurity"],
        effortHours: 8,
    },
    {
        id: "res.system.design.primer",
        title: "System Design Primer",
        platform: "GitHub",
        url: "https://github.com/donnemartin/system-design-primer",
        type: "repository",
        capabilityIds: ["cap.system.design"],
        effortHours: 12,
    },
    {
        id: "res.aws.cloud.essentials",
        title: "AWS Cloud Essentials",
        platform: "AWS",
        url: "https://aws.amazon.com/getting-started/",
        type: "docs",
        capabilityIds: ["cap.cloud.basics"],
        effortHours: 8,
    },
    {
        id: "res.freecodecamp.devops",
        title: "freeCodeCamp DevOps guides",
        platform: "freeCodeCamp",
        url: "https://www.freecodecamp.org/news/tag/devops/",
        type: "article",
        capabilityIds: ["cap.devops.basics"],
        effortHours: 6,
    },
    {
        id: "res.kaggle.learn",
        title: "Kaggle Learn",
        platform: "Kaggle",
        url: "https://www.kaggle.com/learn",
        type: "course",
        capabilityIds: ["cap.data.analysis", "cap.machine.learning"],
        effortHours: 12,
    },
    {
        id: "res.openlearn.managing.people",
        title: "Managing and managing people",
        platform: "OpenLearn",
        url: "https://www.open.edu/openlearn/money-business/leadership-management/managing-and-managing-people/content-section-0",
        type: "course",
        capabilityIds: ["cap.leadership", "cap.executive.leadership"],
        effortHours: 8,
        costType: "free",
        difficulty: "advanced",
        lastVerifiedAt: "2026-08-12",
    },
    {
        id: "res.coursera.corporate.finance",
        title: "Introduction to Corporate Finance",
        platform: "Coursera / Wharton",
        url: "https://www.coursera.org/learn/wharton-finance",
        type: "course",
        capabilityIds: ["cap.business.finance"],
        effortHours: 9,
        costType: "free-audit",
        difficulty: "beginner",
        lastVerifiedAt: "2026-08-12",
    },
    {
        id: "res.coursera.google.project.management",
        title: "Google Project Management Professional Certificate",
        platform: "Coursera / Google",
        url: "https://www.coursera.org/professional-certificates/google-project-management",
        type: "certification",
        capabilityIds: ["cap.project.ownership"],
        effortHours: 120,
        costType: "paid",
        difficulty: "beginner",
        lastVerifiedAt: "2026-08-12",
    },
] as const;
