import type { CapabilityDefinition } from "./capability-catalog.types";

export const CAPABILITY_CATALOG: readonly CapabilityDefinition[] = [
    {
        id: "cap.programming.fundamentals",
        label: "Programming fundamentals",
        category: "technical",
        aliases: ["programming", "coding", "software development basics", "computer science basics"],
        dependsOn: [],
        minCalendarWeeks: 12,
    },
    {
        id: "cap.credential.cs.degree",
        label: "Computer science degree or equivalent",
        category: "credential",
        aliases: [
            "bachelor's degree",
            "bachelors degree",
            "bachelor degree",
            "bachelor's degree in computer science",
            "bachelor's degree in computer science or related field",
            "computer science degree",
            "cs degree",
            "degree in computer science",
            "related field degree",
        ],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 156,
    },
    {
        id: "cap.javascript",
        label: "JavaScript",
        category: "technical",
        aliases: ["js", "javascript", "ecmascript", "node.js", "nodejs"],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 8,
    },
    {
        id: "cap.typescript",
        label: "TypeScript",
        category: "technical",
        aliases: ["ts", "typescript"],
        dependsOn: ["cap.javascript"],
        minCalendarWeeks: 6,
    },
    {
        id: "cap.react",
        label: "React",
        category: "technical",
        aliases: ["react", "react.js", "reactjs"],
        dependsOn: ["cap.javascript"],
        minCalendarWeeks: 8,
    },
    {
        id: "cap.python",
        label: "Python",
        category: "technical",
        aliases: ["python", "python3"],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 8,
    },
    {
        id: "cap.sql",
        label: "SQL",
        category: "technical",
        aliases: ["sql", "databases", "relational databases", "postgres", "postgresql", "mysql"],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 4,
    },
    {
        id: "cap.cybersecurity",
        label: "Cybersecurity fundamentals",
        category: "domain",
        aliases: [
            "cybersecurity",
            "cyber security",
            "information security",
            "infosec",
            "security fundamentals",
            "network security",
        ],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 26,
    },
    {
        id: "cap.security.operations",
        label: "Security operations experience",
        category: "experience",
        aliases: ["soc", "security operations", "incident response", "threat detection", "blue team"],
        dependsOn: ["cap.cybersecurity"],
        minCalendarWeeks: 52,
    },
    {
        id: "cap.security.architecture",
        label: "Security architecture judgment",
        category: "architecture",
        aliases: ["security architecture", "zero trust", "security design", "secure architecture"],
        dependsOn: ["cap.cybersecurity", "cap.system.design"],
        minCalendarWeeks: 39,
    },
    {
        id: "cap.system.design",
        label: "System design",
        category: "architecture",
        aliases: ["system design", "distributed systems", "architecture", "scalability"],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 12,
    },
    {
        id: "cap.cloud.basics",
        label: "Cloud fundamentals",
        category: "technical",
        aliases: ["cloud", "aws", "gcp", "azure", "cloud computing"],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 8,
    },
    {
        id: "cap.devops.basics",
        label: "DevOps fundamentals",
        category: "technical",
        aliases: ["devops", "ci/cd", "docker", "kubernetes", "infrastructure"],
        dependsOn: ["cap.cloud.basics"],
        minCalendarWeeks: 10,
    },
    {
        id: "cap.data.analysis",
        label: "Data analysis",
        category: "technical",
        aliases: ["data analysis", "analytics", "data analytics", "excel", "spreadsheets"],
        dependsOn: [],
        minCalendarWeeks: 6,
    },
    {
        id: "cap.machine.learning",
        label: "Machine learning",
        category: "technical",
        aliases: ["machine learning", "ml", "deep learning", "ai/ml"],
        dependsOn: ["cap.python", "cap.data.analysis"],
        minCalendarWeeks: 16,
    },
    {
        id: "cap.product.sense",
        label: "Product sense",
        category: "domain",
        aliases: ["product", "product management", "product sense", "roadmap planning"],
        dependsOn: [],
        minCalendarWeeks: 12,
    },
    {
        id: "cap.business.finance",
        label: "Business and P&L fluency",
        category: "domain",
        aliases: ["business acumen", "p&l", "finance", "revenue", "go to market", "gtm", "unit economics"],
        dependsOn: ["cap.domain.business"],
        minCalendarWeeks: 26,
    },
    {
        id: "cap.communication",
        label: "Professional communication",
        category: "soft",
        aliases: ["communication", "written communication", "presentation", "stakeholder communication"],
        dependsOn: [],
        minCalendarWeeks: 4,
    },
    {
        id: "cap.collaboration",
        label: "Team collaboration",
        category: "soft",
        aliases: ["teamwork", "collaboration", "cross-functional collaboration"],
        dependsOn: ["cap.communication"],
        minCalendarWeeks: 8,
    },
    {
        id: "cap.leadership",
        label: "People leadership",
        category: "leadership",
        aliases: ["leadership", "people management", "mentoring", "managing teams", "team lead"],
        dependsOn: ["cap.collaboration"],
        minCalendarWeeks: 52,
    },
    {
        id: "cap.executive.leadership",
        label: "Executive leadership readiness",
        category: "leadership",
        aliases: ["executive leadership", "ceo skills", "c-suite", "board communication", "executive presence"],
        dependsOn: ["cap.leadership", "cap.business.finance"],
        minCalendarWeeks: 78,
    },
    {
        id: "cap.project.ownership",
        label: "Project ownership",
        category: "responsibility",
        aliases: ["ownership", "project ownership", "end-to-end ownership", "delivery ownership"],
        dependsOn: ["cap.collaboration"],
        minCalendarWeeks: 16,
    },
    {
        id: "cap.domain.business",
        label: "Business domain fluency",
        category: "domain",
        aliases: ["domain knowledge", "industry knowledge"],
        dependsOn: [],
        minCalendarWeeks: 12,
    },
    {
        id: "cap.interview.ready",
        label: "Interview readiness",
        category: "soft",
        aliases: ["interviewing", "technical interviews", "behavioral interviews"],
        dependsOn: ["cap.communication"],
        minCalendarWeeks: 4,
    },
    {
        id: "cap.portfolio",
        label: "Portfolio and evidence",
        category: "experience",
        aliases: ["portfolio", "projects", "github portfolio", "case studies"],
        dependsOn: ["cap.programming.fundamentals"],
        minCalendarWeeks: 8,
    },
    {
        id: "cap.professional.experience",
        label: "Professional experience",
        category: "experience",
        aliases: ["work experience", "professional experience", "internship", "job experience"],
        dependsOn: ["cap.portfolio"],
        minCalendarWeeks: 52,
    },
] as const;

export const CAPABILITY_BY_ID: ReadonlyMap<string, CapabilityDefinition> = new Map(
    CAPABILITY_CATALOG.map((capability) => [capability.id, capability])
);
