export const GITHUB_API_HEADERS = {
    Accept: "application/vnd.github+json",
    "User-Agent": "CareerCoach-App",
} as const;

export const MAX_REPOSITORIES_TO_ANALYZE = 12;
export const MAX_SKILLS_TO_STORE = 40;
export const MAX_MANIFEST_REPOSITORIES_TO_ANALYZE = 8;
export const REPOSITORY_LIST_PER_PAGE = 100;
export const MAX_MANIFEST_FILES_PER_REPOSITORY = 20;

export const MANIFEST_PATHS = [
    "package.json",
    "requirements.txt",
    "pyproject.toml",
    "Pipfile",
    "go.mod",
    "Cargo.toml",
    "composer.json",
    "Gemfile",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "README.md",
] as const;

export const MANIFEST_SKILL_PATTERNS: { pattern: RegExp; skill: string }[] = [
    { pattern: /"react(?:-dom|-router-dom)?"\s*:|"@types\/react"|"@reduxjs\/toolkit"/i, skill: "React" },
    { pattern: /"next"\s*:|"next-auth"/i, skill: "Next.js" },
    { pattern: /"vue"|"\@vue\/|pinia|nuxt/i, skill: "Vue.js" },
    { pattern: /"angular"|"\@angular\//i, skill: "Angular" },
    { pattern: /express|nestjs|koa|fastify|hapi/i, skill: "Node.js" },
    { pattern: /typescript/i, skill: "TypeScript" },
    { pattern: /javascript/i, skill: "JavaScript" },
    { pattern: /tailwindcss|tailwind/i, skill: "Tailwind CSS" },
    { pattern: /sass|scss/i, skill: "SCSS" },
    { pattern: /mongodb|mongoose/i, skill: "MongoDB" },
    { pattern: /postgres|postgresql|typeorm|prisma/i, skill: "PostgreSQL" },
    { pattern: /mysql|mariadb/i, skill: "MySQL" },
    { pattern: /redis/i, skill: "Redis" },
    { pattern: /docker/i, skill: "Docker" },
    { pattern: /kubernetes|k8s/i, skill: "Kubernetes" },
    { pattern: /aws-|amazon web services|aws/i, skill: "AWS" },
    { pattern: /azure/i, skill: "Azure" },
    { pattern: /gcp|google cloud/i, skill: "GCP" },
    { pattern: /python|django|flask|fastapi/i, skill: "Python" },
    { pattern: /java|spring-boot|springframework/i, skill: "Java" },
    { pattern: /c#|\.csproj|dotnet|asp\.net/i, skill: "C#" },
    { pattern: /php|laravel|symfony/i, skill: "PHP" },
    { pattern: /ruby|rails/i, skill: "Ruby" },
    { pattern: /go[^a-z]|golang/i, skill: "Go" },
    { pattern: /rust|cargo/i, skill: "Rust" },
    { pattern: /graphql|apollo/i, skill: "GraphQL" },
    { pattern: /jest|vitest|mocha|pytest|junit/i, skill: "Testing" },
    { pattern: /terraform/i, skill: "Terraform" },
];

export const PACKAGE_SKILL_MAP: Record<string, string> = {
    "@angular/core": "Angular",
    "@apollo/client": "GraphQL",
    "@aws-sdk/client-s3": "AWS",
    "@azure/storage-blob": "Azure",
    "@chakra-ui/react": "Chakra UI",
    "@emotion/react": "CSS-in-JS",
    "@emotion/styled": "CSS-in-JS",
    "@grpc/grpc-js": "gRPC",
    "@nestjs/microservices": "Microservices",
    "@mui/material": "Material UI",
    "@nestjs/common": "NestJS",
    "@prisma/client": "Prisma",
    "@remix-run/react": "Remix",
    "@reduxjs/toolkit": "Redux",
    "@sveltejs/kit": "SvelteKit",
    "@tanstack/react-query": "React Query",
    "@testing-library/react": "Testing",
    "@vue/runtime-core": "Vue.js",
    amqplib: "RabbitMQ",
    axios: "REST APIs",
    bootstrap: "Bootstrap",
    cypress: "Testing",
    drizzle: "Drizzle ORM",
    express: "Express",
    fastify: "Fastify",
    firebase: "Firebase",
    graphql: "GraphQL",
    ioredis: "Redis",
    jest: "Testing",
    kafkajs: "Kafka",
    koa: "Koa",
    mongoose: "MongoDB",
    mysql2: "MySQL",
    nestjs: "NestJS",
    next: "Next.js",
    "next-auth": "NextAuth",
    nextauth: "NextAuth",
    nuxt: "Nuxt",
    openai: "OpenAI",
    playwright: "Testing",
    prisma: "Prisma",
    pytest: "Testing",
    react: "React",
    "react-dom": "React",
    "react-hook-form": "React Hook Form",
    "react-native": "React Native",
    "react-router-dom": "React Router",
    redux: "Redux",
    sequelize: "Sequelize",
    "socket.io": "WebSockets",
    "styled-components": "CSS-in-JS",
    svelte: "Svelte",
    tailwindcss: "Tailwind CSS",
    three: "Three.js",
    trpc: "tRPC",
    typeorm: "TypeORM",
    typescript: "TypeScript",
    vercel: "Vercel",
    vite: "Vite",
    vue: "Vue.js",
    vuetify: "Vuetify",
    webpack: "Webpack",
    zod: "Zod",
};

export const ROOT_FILE_SKILL_PATTERNS: { pattern: RegExp; skill: string }[] = [
    { pattern: /^dockerfile$/i, skill: "Docker" },
    { pattern: /^docker-compose(\..+)?\.ya?ml$/i, skill: "Docker" },
    { pattern: /^compose\.ya?ml$/i, skill: "Docker" },
    { pattern: /^terraform\.(tf|tfvars)$/i, skill: "Terraform" },
    { pattern: /\.tf$/i, skill: "Terraform" },
    { pattern: /^serverless\.ya?ml$/i, skill: "Serverless" },
    { pattern: /^vercel\.json$/i, skill: "Vercel" },
];

export const SKILL_ALIASES: Record<string, string> = {
    "asp.net": "ASP.NET",
    c: "C",
    "c#": "C#",
    "c-sharp": "C#",
    "c++": "C++",
    css: "CSS",
    dockerfile: "Docker",
    golang: "Go",
    html: "HTML",
    javascript: "JavaScript",
    mongodb: "MongoDB",
    "next.js": "Next.js",
    nextjs: "Next.js",
    "node.js": "Node.js",
    nodejs: "Node.js",
    postgres: "PostgreSQL",
    postgresql: "PostgreSQL",
    rabbitmq: "RabbitMQ",
    react: "React",
    reactjs: "React",
    scss: "SCSS",
    sql: "SQL",
    tailwind: "Tailwind CSS",
    tailwindcss: "Tailwind CSS",
    terraform: "Terraform",
    typescript: "TypeScript",
    vue: "Vue.js",
    vuejs: "Vue.js",
};
